/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class Poem extends cloudDatabase.DatabaseObject {
  id: number;
  title: string = "";
  dynasty: string;
  writer: string = "";
  content: string = "";
  type: string;
  remark: string;
  shangxi: string;
  translation: string;

  naturalbase_ClassName(): string {
    return 'Poem';
  }
}

export { Poem };