/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */
import { cloudDatabase } from '@kit.CloudFoundationKit';

class Xiehouyu extends cloudDatabase.DatabaseObject {
  id: number;
  riddle: string = "";
  answer: string = "";

  naturalbase_ClassName(): string {
    return 'Xiehouyu';
  }
}

export { Xiehouyu };