export const paperCuttingImageList: string[] = [
  'papercutting/paper1.jpg',
  'papercutting/paper2.jpg',
  'papercutting/paper3.jpg',
  'papercutting/paper4.jpeg',
  'papercutting/paper5.jpeg',
  'papercutting/paper6.jpeg'
];

export const embroideryImageList: string[] = [
  'embroidery/embroidery1.png',
  'embroidery/embroidery2.jpg',
  'embroidery/embroidery3.jpg',
  'embroidery/embroidery4.jpg',
  'embroidery/embroidery5.jpg'
];

export const ceramicImageList: string[] = [
  'ceramic/ceramic1.jpg',
  'ceramic/ceramic2.jpg',
  'ceramic/ceramic3.jpeg',
  'ceramic/ceramic4.jpg',
  'ceramic/ceramic5.jpg'
];

export const bambooImageList: string[] = [
  'bamboo/bamboo1.jpg',
  'bamboo/bamboo2.jpg',
  'bamboo/bamboo3.jpg',
  'bamboo/bamboo4.jpeg',
  'bamboo/bamboo5.jpeg',
  'bamboo/bamboo6.jpeg'
];

export const clayFigurineImageList: string[] = [
  'clayFigurine/clayFigurine1.jpg',
  'clayFigurine/clayFigurine2.jpg',
  'clayFigurine/clayFigurine3.jpg',
  'clayFigurine/clayFigurine4.jpg',
  'clayFigurine/clayFigurine5.jpg'
];

export const ChineseShadowPuppetryImageList: string[] = [
  'ChineseShadowPuppetry/shadow1.jpg',
  'ChineseShadowPuppetry/shadow2.png',
  'ChineseShadowPuppetry/shadow3.jpg'
];

export const DragonDanceAndLionDance: string[] = [
  'DragonDanceAndLionDance/dance1.jpg',
  'DragonDanceAndLionDance/dance2.png',
  'DragonDanceAndLionDance/dance3.jpg'
];