/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Collection {
    constructor() {
        this.id = undefined;
        this.userId = 0;
        this.spotId = 0;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }

    setSpotId(spotId) {
        this.spotId = spotId;
    }

    getSpotId() {
        return this.spotId;
    }
}

Collection.className = 'Collection';

export {Collection}