/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class mySpot {
    constructor() {
        this.id = undefined;
        this.name = "null";
        this.summary = undefined;
        this.category = "所有分类";
        this.rating = undefined;
        this.ticketPrice = undefined;
        this.openingHours = undefined;
        this.imageUrl = undefined;
        this.latitude = undefined;
        this.longitude = undefined;
        this.cityCode = undefined;
        this.cityId = undefined;
        this.cityName = undefined;
        this.areaName = undefined;
        this.address = undefined;
        this.proId = undefined;
        this.proName = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }

    setSummary(summary) {
        this.summary = summary;
    }

    getSummary() {
        return this.summary;
    }

    setCategory(category) {
        this.category = category;
    }

    getCategory() {
        return this.category;
    }

    setRating(rating) {
        this.rating = rating;
    }

    getRating() {
        return this.rating;
    }

    setTicketPrice(ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    getTicketPrice() {
        return this.ticketPrice;
    }

    setOpeningHours(openingHours) {
        this.openingHours = openingHours;
    }

    getOpeningHours() {
        return this.openingHours;
    }

    setImageUrl(imageUrl) {
        this.imageUrl = imageUrl;
    }

    getImageUrl() {
        return this.imageUrl;
    }

    setLatitude(latitude) {
        this.latitude = latitude;
    }

    getLatitude() {
        return this.latitude;
    }

    setLongitude(longitude) {
        this.longitude = longitude;
    }

    getLongitude() {
        return this.longitude;
    }

    setCityCode(cityCode) {
        this.cityCode = cityCode;
    }

    getCityCode() {
        return this.cityCode;
    }

    setCityId(cityId) {
        this.cityId = cityId;
    }

    getCityId() {
        return this.cityId;
    }

    setCityName(cityName) {
        this.cityName = cityName;
    }

    getCityName() {
        return this.cityName;
    }

    setAreaName(areaName) {
        this.areaName = areaName;
    }

    getAreaName() {
        return this.areaName;
    }

    setAddress(address) {
        this.address = address;
    }

    getAddress() {
        return this.address;
    }

    setProId(proId) {
        this.proId = proId;
    }

    getProId() {
        return this.proId;
    }

    setProName(proName) {
        this.proName = proName;
    }

    getProName() {
        return this.proName;
    }
}

mySpot.className = 'mySpot';

export {mySpot}