export class CommonConstants {
  static readonly AIPassword: string = 'MvZBmiYOGqZwMwImGcDs:RnzZhRIwimchQTzsnMss'
  static readonly AIModel: string = 'generalv3.5';
  static readonly AIUrl: string = 'https://spark-api-open.xf-yun.com/v1/chat/completions';

  static readonly ZhiPuKey: string = "e834ce28afda20edc1eb5ce580d4b747.bwuQUbcirioD3udl"
  static readonly ZhiPuCreateImageURL:string="https://open.bigmodel.cn/api/paas/v4/images/generations?"
}