export class CommonConstants {
  // 讯飞星火
  static readonly AIPassword: string = 'MvZBmiYOGqZwMwImGcDs:RnzZhRIwimchQTzsnMss';

  static readonly AIModel: string = 'generalv3.5';
  static readonly AIUrl: string = 'https://spark-api-open.xf-yun.com/v1/chat/completions';
  // 质谱清言
  static readonly ZhiPuKey: string = "d64ee3acf502f827dbd5c55ce9a2d9d2.0o0iCPXKYZx3G3Bk"
  static readonly ZhiPuCreateImageURL: string = "https://open.bigmodel.cn/api/paas/v4/images/generations?" // 文生图API
  static readonly CreateImageModelCode: string = "cogview-3-plus"
  static readonly ZhiPu_GLM_4: string = "https://open.bigmodel.cn/api/paas/v4/chat/completions"
  //
  static readonly IdiomSystemHeadImg: ResourceStr = $r('app.media.IdiomSystem')
  static readonly expTypeKnowledge: string = 'knowledge'
  static readonly expTypeCulture: string = 'culture'
  static readonly expTypeGame: string = 'game'
  static readonly fetchNumber: number = 40
}




