/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class BrowsingHistory {
    constructor() {
        this.id = undefined;
        this.viewTime = undefined;
        this.viewCount = undefined;
        this.type = "spot";
        this.userId = "1544893736041851904";
        this.poemId = 1;
        this.spotId = 4;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setViewTime(viewTime) {
        this.viewTime = viewTime;
    }

    getViewTime() {
        return this.viewTime;
    }

    setViewCount(viewCount) {
        this.viewCount = viewCount;
    }

    getViewCount() {
        return this.viewCount;
    }

    setType(type) {
        this.type = type;
    }

    getType() {
        return this.type;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }

    setPoemId(poemId) {
        this.poemId = poemId;
    }

    getPoemId() {
        return this.poemId;
    }

    setSpotId(spotId) {
        this.spotId = spotId;
    }

    getSpotId() {
        return this.spotId;
    }
}

BrowsingHistory.className = 'BrowsingHistory';

export {BrowsingHistory}