/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Idiom {
    constructor() {
        this.id = undefined;
        this.word = undefined;
        this.abbr = undefined;
        this.data = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setWord(word) {
        this.word = word;
    }

    getWord() {
        return this.word;
    }

    setAbbr(abbr) {
        this.abbr = abbr;
    }

    getAbbr() {
        return this.abbr;
    }

    setData(data) {
        this.data = data;
    }

    getData() {
        return this.data;
    }
}

Idiom.className = 'Idiom';

export {Idiom}