/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class myOrder {
    constructor() {
        this.order_id = undefined;
        this.spot_id = 0;
        this.order_time = undefined;
        this.order_status = "1";
        this.total_amount = 1.0;
        this.quantity = undefined;
        this.order_type = undefined;
        this.user_id = "0";
    }

    setOrder_id(order_id) {
        this.order_id = order_id;
    }

    getOrder_id() {
        return this.order_id;
    }

    setSpot_id(spot_id) {
        this.spot_id = spot_id;
    }

    getSpot_id() {
        return this.spot_id;
    }

    setOrder_time(order_time) {
        this.order_time = order_time;
    }

    getOrder_time() {
        return this.order_time;
    }

    setOrder_status(order_status) {
        this.order_status = order_status;
    }

    getOrder_status() {
        return this.order_status;
    }

    setTotal_amount(total_amount) {
        this.total_amount = total_amount;
    }

    getTotal_amount() {
        return this.total_amount;
    }

    setQuantity(quantity) {
        this.quantity = quantity;
    }

    getQuantity() {
        return this.quantity;
    }

    setOrder_type(order_type) {
        this.order_type = order_type;
    }

    getOrder_type() {
        return this.order_type;
    }

    setUser_id(user_id) {
        this.user_id = user_id;
    }

    getUser_id() {
        return this.user_id;
    }
}

myOrder.className = 'myOrder';

export {myOrder}