/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Poem {
    constructor() {
        this.numId = undefined;
        this.id = undefined;
        this.title = undefined;
        this.dynasty = undefined;
        this.writer = undefined;
        this.content = undefined;
        this.type = undefined;
        this.remark = undefined;
        this.shangxi = undefined;
        this.translation = undefined;
    }

    setNumId(numId) {
        this.numId = numId;
    }

    getNumId() {
        return this.numId;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setDynasty(dynasty) {
        this.dynasty = dynasty;
    }

    getDynasty() {
        return this.dynasty;
    }

    setWriter(writer) {
        this.writer = writer;
    }

    getWriter() {
        return this.writer;
    }

    setContent(content) {
        this.content = content;
    }

    getContent() {
        return this.content;
    }

    setType(type) {
        this.type = type;
    }

    getType() {
        return this.type;
    }

    setRemark(remark) {
        this.remark = remark;
    }

    getRemark() {
        return this.remark;
    }

    setShangxi(shangxi) {
        this.shangxi = shangxi;
    }

    getShangxi() {
        return this.shangxi;
    }

    setTranslation(translation) {
        this.translation = translation;
    }

    getTranslation() {
        return this.translation;
    }
}

Poem.className = 'Poem';

export {Poem}