/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Poet {
    constructor() {
        this.id = undefined;
        this.title = "";
        this.dynasty = "";
        this.writer = "";
        this.content = "";
        this.type = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setDynasty(dynasty) {
        this.dynasty = dynasty;
    }

    getDynasty() {
        return this.dynasty;
    }

    setWriter(writer) {
        this.writer = writer;
    }

    getWriter() {
        return this.writer;
    }

    setContent(content) {
        this.content = content;
    }

    getContent() {
        return this.content;
    }

    setType(type) {
        this.type = type;
    }

    getType() {
        return this.type;
    }
}

Poet.className = 'Poet';

export {Poet}