/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Sentence {
    constructor() {
        this.id = undefined;
        this.from = undefined;
        this.text = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setFrom(from) {
        this.from = from;
    }

    getFrom() {
        return this.from;
    }

    setText(text) {
        this.text = text;
    }

    getText() {
        return this.text;
    }
}

Sentence.className = 'Sentence';

export {Sentence}