/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Writer {
    constructor() {
        this.id = undefined;
        this.name = undefined;
        this.simpleIntro = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }

    setSimpleIntro(simpleIntro) {
        this.simpleIntro = simpleIntro;
    }

    getSimpleIntro() {
        return this.simpleIntro;
    }
}

Writer.className = 'Writer';

export {Writer}