/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Xiehouyu {
    constructor() {
        this.id = undefined;
        this.riddle = "无";
        this.answer = " 无";
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setRiddle(riddle) {
        this.riddle = riddle;
    }

    getRiddle() {
        return this.riddle;
    }

    setAnswer(answer) {
        this.answer = answer;
    }

    getAnswer() {
        return this.answer;
    }
}

Xiehouyu.className = 'Xiehouyu';

export {Xiehouyu}