export default class Constants {

  static readonly ACCOUNT_POSITION_X: string = '46%';
  static readonly PERCENT_50 = '50%';
  static readonly PERCENT_80 = '80%';
  static readonly PERCENT_90 = '90%';
  static readonly CLIP_RATIO_FOLD = '65%';
  static readonly CLIP_RATIO_PAD = '39%';
  static readonly CIRCLE_RATIO_Y = '14%';
  static readonly CLIP_RATIO_PHONE = 0.73;
  static readonly CLIP_RATIO = '73%';
  static readonly CLIP_WIDTH = '86.6%';
  static readonly CLIP_MARGIN = '6.7%';
  static readonly IMAGE_RATIO_PHONE = '46%';
  static readonly IMAGE_RATIO_FOLD = '63%';
  static readonly IMAGE_RATIO_PAD = '75%';
  /**
   *  space:SMALL Middle Large
   */
  static readonly SMALL_SPACE: number = 5;
  static readonly MIDDLE_SPACE: number = 10;
  static readonly LARGE_SPACE: number = 15;
  static readonly LLARGE_SPACE: number = 24;
  static readonly ROW_SPACE: number = 16;
  static readonly NAVIGATION_HEIGHT: number = 56;
  static readonly PADDING_PAGE = 12;
  /**
   * duration
   */
  static readonly SHORT_ANIMATION_DURATION: number = 200;
  static readonly DEFAULT_DURATION: number = 300;
  static readonly LONG_ANIMATION_DURATION: number = 500;
  /**
   * other
   */
  static readonly REFRESH_DELAY: number = 1000;
  static readonly ACHIEVEMENT_LIST_LANES_SM: number = 3;
  static readonly ACHIEVEMENT_LIST_LANES_MD: number = 5
  static readonly ACHIEVEMENT_LIST_LANES_LG: number = 6;
  static readonly COUNT_TWO: number = 2;
  static readonly PHOTO_PADDING_BOTTOM: number = 30;
  //页面距离顶部高度
  static readonly HEADER_HEIGHT_PAGE = 20;
  //barheight
  static readonly BAR_HEIGHT_PAGE = 40;
  static readonly TOP_HEIGHT_PAGE = 40;
}
