export class AppConstants {
  /**
   * 100 percent.
   */
  static readonly FULL_PERCENT: string = '100%';
  /**
   * 20 percent.
   */
  static readonly TAB_PERCENT: string = '15%';
  /**
   * Tab bar font weight.
   */
  static readonly TAB_FONT_WEIGHT: number = 600;
  /**
   * Default status height
   */
  static readonly DEFAULT_STATUS_HEIGHT: number = 32;
  static readonly TAB_HEIGHT: number = 56;

  static readonly MAIN_BOTTOM_MARGIN: number = 16;

}