/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class BrowsingHistory {
    constructor() {
        this.id = undefined;
        this.userId = 0;
        this.spotId = 0;
        this.viewTime = undefined;
        this.viewCount = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }

    setSpotId(spotId) {
        this.spotId = spotId;
    }

    getSpotId() {
        return this.spotId;
    }

    setViewTime(viewTime) {
        this.viewTime = viewTime;
    }

    getViewTime() {
        return this.viewTime;
    }

    setViewCount(viewCount) {
        this.viewCount = viewCount;
    }

    getViewCount() {
        return this.viewCount;
    }
}

BrowsingHistory.className = 'BrowsingHistory';

export {BrowsingHistory}