/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

import Long from 'long';

class Spot {
    constructor() {
        this.id = undefined;
        this.name = "null";
        this.summary = undefined;
        this.category = "全部分类";
        this.rating = undefined;
        this.ticketPrice = undefined;
        this.openingHours = undefined;
        this.cityId = Long.fromString('0');
        this.areaName = undefined;
        this.address = undefined;
        this.imageUrl = undefined;
    }


    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }

    setSummary(summary) {
        this.summary = summary;
    }

    getSummary() {
        return this.summary;
    }

    setCategory(category) {
        this.category = category;
    }

    getCategory() {
        return this.category;
    }

    setRating(rating) {
        this.rating = rating;
    }

    getRating() {
        return this.rating;
    }

    setTicketPrice(ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    getTicketPrice() {
        return this.ticketPrice;
    }

    setOpeningHours(openingHours) {
        this.openingHours = openingHours;
    }

    getOpeningHours() {
        return this.openingHours;
    }

    setCityId(cityId) {
        this.cityId = cityId;
    }

    getCityId() {
        return this.cityId;
    }

    setAreaName(areaName) {
        this.areaName = areaName;
    }

    getAreaName() {
        return this.areaName;
    }

    setAddress(address) {
        this.address = address;
    }

    getAddress() {
        return this.address;
    }

    setImageUrl(imageUrl) {
        this.imageUrl = imageUrl;
    }

    getImageUrl() {
        return this.imageUrl;
    }
}

Spot.className = 'Spot';

export {Spot}