/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Comment {
    constructor() {
        this.id = undefined;
        this.momentid = undefined;
        this.text = undefined;
        this.image = undefined;
        this.uid = undefined;
        this.time = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setMomentid(momentid) {
        this.momentid = momentid;
    }

    getMomentid() {
        return this.momentid;
    }

    setText(text) {
        this.text = text;
    }

    getText() {
        return this.text;
    }

    setImage(image) {
        this.image = image;
    }

    getImage() {
        return this.image;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }

    setTime(time) {
        this.time = time;
    }

    getTime() {
        return this.time;
    }
}

Comment.className = 'Comment';

export {Comment}