/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Comment {
    constructor() {
        this.id = undefined;
        this.momentid = undefined;
        this.text = undefined;
        this.image = undefined;
        this.photo = undefined;
        this.name = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setMomentid(momentid) {
        this.momentid = momentid;
    }

    getMomentid() {
        return this.momentid;
    }

    setText(text) {
        this.text = text;
    }

    getText() {
        return this.text;
    }

    setImage(image) {
        this.image = image;
    }

    getImage() {
        return this.image;
    }

    setPhoto(photo) {
        this.photo = photo;
    }

    getPhoto() {
        return this.photo;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }
}

Comment.className = 'Comment';

export {Comment}