/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class FriendMoment {
    constructor() {
        this.id = undefined;
        this.userId = "1544893736041851904";
        this.text = undefined;
        this.image = undefined;
        this.video = undefined;
        this.good = undefined;
        this.location = undefined;
        this.userPhoto = undefined;
        this.userName = undefined;
        this.time = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }

    setText(text) {
        this.text = text;
    }

    getText() {
        return this.text;
    }

    setImage(image) {
        this.image = image;
    }

    getImage() {
        return this.image;
    }

    setVideo(video) {
        this.video = video;
    }

    getVideo() {
        return this.video;
    }

    setGood(good) {
        this.good = good;
    }

    getGood() {
        return this.good;
    }

    setLocation(location) {
        this.location = location;
    }

    getLocation() {
        return this.location;
    }

    setUserPhoto(userPhoto) {
        this.userPhoto = userPhoto;
    }

    getUserPhoto() {
        return this.userPhoto;
    }

    setUserName(userName) {
        this.userName = userName;
    }

    getUserName() {
        return this.userName;
    }

    setTime(time) {
        this.time = time;
    }

    getTime() {
        return this.time;
    }
}

FriendMoment.className = 'FriendMoment';

export {FriendMoment}