/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class Good {
    constructor() {
        this.itemId = undefined;
        this.userId = undefined;
    }

    setItemId(itemId) {
        this.itemId = itemId;
    }

    getItemId() {
        return this.itemId;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }
}

Good.className = 'Good';

export {Good}