/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class User {
    constructor() {
        this.userId = undefined;
        this.userName = undefined;
        this.userPhoto = undefined;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }

    setUserName(userName) {
        this.userName = userName;
    }

    getUserName() {
        return this.userName;
    }

    setUserPhoto(userPhoto) {
        this.userPhoto = userPhoto;
    }

    getUserPhoto() {
        return this.userPhoto;
    }
}

User.className = 'User';

export {User}